image: golang:1.13.5

variables:
  PKG_NAME: gitlab.com/ignitionrobotics/web/ign-go.git
  PKG_DIR: $GOPATH/src/$(dirname $PKG_NAME)
  MYSQL_DATABASE: "root"
  MYSQL_ROOT_PASSWORD: "root"

before_script:
  - go version
  - mkdir -p $PKG_DIR
  - mount -o bind $CI_PROJECT_DIR $PKG_DIR
  - cd $PKG_DIR
  - go get

stages:
  - format
  - lint
  - test
  - build

format:
  stage: format
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

lint:
  stage: lint
  script:
    - lint=$(golint $(go list ./...) | grep -v ".pb.go") && if [[ ! -z $lint ]]; then echo $lint && exit 1; fi


vet:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)


coverage:
  stage: test
  script:
    - bash coverage.sh
    - bash <(curl -s https://codecov.io/bash)
  services:
    - mysql:5.7


build:
  stage: build
  script:
    - go build