image: golang:1.13.5

variables:
  MYSQL_DATABASE: "root"
  MYSQL_ROOT_PASSWORD: "root"

before_script:
  - go version
  - go get
  - go get -u golang.org/x/lint
  - pwd
  - echo $GOPATH
  - export PATH=$PATH:$GOPATH/bin

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $GOPATH/pkg/mod

stages:
  - formatting
  - linting
  - testing
  - building

format:
  stage: formatting
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

lint:
  stage: linting
  script:
    - golint -set_exit_status $(go list ./... | grep -v /vendor/)


vet:
  stage: testing
  script:
    - go vet $(go list ./... | grep -v /vendor/)
  services:
    - mysql:5.7

test:
  stage: testing
  script:
    - go test $(go list ./... | grep -v /vendor/)
  services:
    - mysql:5.7

race:
  stage: testing
  script:
    - go test -race $(go list ./... | grep -v /vendor/)
  services:
    - mysql:5.7

memory_sanitize:
  stage: testing
  script:
    - go test -msan $(go list ./... | grep -v /vendor/)
  services:
    - mysql:5.7

coverage:
  stage: testing
  script:
    - bash coverage.sh
    - bash <(curl -s https://codecov.io/bash)
  services:
    - mysql:5.7


build:
  stage: building
  script:
    - go build
